AGGREGATION = {
    "Tn(Nunukan)": "mean",
    "Tx(Nunukan)": "mean",
    "Tavg(Nunukan)": "mean",
    "RH_avg(Nunukan)": "mean",
    "RR(Nunukan)": "sum",
    "ss(Nunukan)": "sum",
    "ff_x(Nunukan)": "mean",
    "ddd_x(Nunukan)": "mean",
    "ff_avg(Nunukan)": "mean",
    
    "Tn(Iskandar)": "mean",
    "Tx(Iskandar)": "mean",
    "Tavg(Iskandar)": "mean",
    "RH_avg(Iskandar)": "mean",
    "RR(Iskandar)": "sum",
    "ss(Iskandar)": "sum",
    "ff_x(Iskandar)": "mean",
    "ddd_x(Iskandar)": "mean",
    "ff_avg(Iskandar)": "mean",
    
    "Tn(Oesman)": "mean",
    "Tx(Oesman)": "mean",
    "Tavg(Oesman)": "mean",
    "RH_avg(Oesman)": "mean",
    "RR(Oesman)": "sum",
    "ss(Oesman)": "sum",
    "ff_x(Oesman)": "mean",
    "ddd_x(Oesman)": "mean",
    "ff_avg(Oesman)": "mean",
    
    "Tn(Japura)": "mean",
    "Tx(Japura)": "mean",
    "Tavg(Japura)": "mean",
    "RH_avg(Japura)": "mean",
    "RR(Japura)": "sum",
    "ss(Japura)": "sum",
    "ff_x(Japura)": "mean",
    "ddd_x(Japura)": "mean",
    "ff_avg(Japura)": "mean",
    
    "Tn(Sumatera Selatan)": "mean",
    "Tx(Sumatera Selatan)": "mean",
    "Tavg(Sumatera Selatan)": "mean",
    "RH_avg(Sumatera Selatan)": "mean",
    "RR(Sumatera Selatan)": "sum",
    "ss(Sumatera Selatan)": "sum",
    "ff_x(Sumatera Selatan)": "mean",
    "ddd_x(Sumatera Selatan)": "mean",
    "ff_avg(Sumatera Selatan)": "mean"
}
